// valid values for type: UserTask, DataObject, DataStore, ServiceTask
module.exports.REST_SHOPIFY = {
    label_tag: 'Group',
    label_path: 'Endpoint',
    label_method: 'Operation',
    tags: [
        { name: 'Access', value: 'access', paths: [
            { name: 'AccessScope', value: '/admin/oauth/access_scopes.json', methods: ["GET"] },
            { name: 'StorefrontAccessToken', value: '/admin/api/{SELECTED_VERSION}/storefront_access_tokens.json', methods: ["GET","POST"] },
            { name: 'StorefrontAccessToken by Id', value: '/admin/api/{SELECTED_VERSION}/storefront_access_tokens/#{storefront_access_token_id}.json', methods:["DELETE"]},
        ]},
        { name: 'Analytics', value: 'analytics', paths: [
            { name: 'Report', value: '/admin/api/{SELECTED_VERSION}/reports.json', methods: ["GET", "POST"] },
            { name: 'Report by Id', value: '/admin/api/{SELECTED_VERSION}/reports/#{report_id}.json', methods:["GET", "PUT", "DELETE"]}
        ]},
        { name: 'Billing', value: 'billing', paths: [
            { name: 'ApplicationCharge', value: '/admin/api/{SELECTED_VERSION}/application_charges.json', methods: ["GET", "POST"] },
            { name: 'ApplicationCharge by Id', value: '/admin/api/{SELECTED_VERSION}/application_charges/#{application_charge_id}.json', methods: ["GET"] },
            { name: 'ApplicationCharge Activate by Id', value: '/admin/api/{SELECTED_VERSION}/application_charges/#{application_charge_id}/activate.json', methods: ["POST"] },
            { name: 'ApplicationCredit', value: '/admin/api/{SELECTED_VERSION}/application_credits.json', methods: ["GET", "POST"] },
            { name: 'ApplicationCredit by Id', value: '/admin/api/{SELECTED_VERSION}/application_credits/#{application_credit_id}.json', methods: ["GET"] },
            { name: 'RecurringApplicationCharge', value: '/admin/api/{SELECTED_VERSION}/recurring_application_charges.json', methods: ["GET", "POST"] },
            { name: 'RecurringApplicationCharge by Id', value: '/admin/api/{SELECTED_VERSION}/recurring_application_charges/#{recurring_application_charge_id}.json', methods: ["GET", "DELETE"] },
            { name: 'RecurringApplicationCharge Activate by Id', value: '/admin/api/{SELECTED_VERSION}/recurring_application_charges/#{recurring_application_charge_id}/activate.json', methods: ["POST"] },
            { name: 'UsageCharge', value: '/admin/api/{SELECTED_VERSION}/recurring_application_charges/#{recurring_application_charge_id}/usage_charges.json', methods: ["GET", "POST"] },
            { name: 'UsageCharge by Id', value: '/admin/api/{SELECTED_VERSION}/recurring_application_charges/#{recurring_application_charge_id}/usage_charges/#{usage_charge_id}.json', methods: ["GET"] },
        ]},
        { name: 'Customer', value: 'customer', paths: [
            { name: 'Customer', value: '/admin/api/{SELECTED_VERSION}/customers.json', methods: ["GET", "POST"] },
            { name: 'Customer by Id', value: '/admin/api/{SELECTED_VERSION}/customers/#{customer_id}.json', methods: ["GET", "PUT", "DELETE"] },
            { name: 'Customer Activate by Id', value: '/admin/api/{SELECTED_VERSION}/customers/#{customer_id}/account_activation_url.json', methods: ["POST"] },
            { name: 'Customer Invite by Id', value: '/admin/api/{SELECTED_VERSION}/customers/#{customer_id}/send_invite.json', methods: ["POST"] },
            { name: 'Customer Count', value: '/admin/api/{SELECTED_VERSION}/customers/count.json', methods: ["GET"] },
            { name: 'Customer Orders', value: '/admin/api/{SELECTED_VERSION}/customers/#{customer_id}/orders.json', methods: ["GET"] },
            { name: 'CustomerAddress', value: '/admin/api/{SELECTED_VERSION}/customers/#{customer_id}/addresses.json', methods: ["GET", "POST"] },
            { name: 'CustomerAddress by Id', value: '/admin/api/{SELECTED_VERSION}/customers/#{customer_id}/addresses/#{address_id}.json', methods: ["GET", "PUT", "DELETE"] },
            { name: 'CustomerAddress Default by Id', value: '/admin/api/{SELECTED_VERSION}/customers/#{customer_id}/addresses/#{address_id}/default.json', methods: ["POST"] },
            { name: 'CustomerSavedSearch', value: '/admin/api/{SELECTED_VERSION}/customer_saved_searches.json', methods: ["GET", "POST"] },
            { name: 'CustomerSavedSearch by Id', value: '/admin/api/{SELECTED_VERSION}/customer_saved_searches/#{customer_saved_search_id}.json', methods: ["GET", "PUT", "DELETE"] },
            { name: 'CustomerSavedSearch Count', value: '/admin/api/{SELECTED_VERSION}/customer_saved_searches/count.json', methods: ["GET"] },
        ]},
        { name: 'Discount', value: 'discount', paths: [
            { name: 'DiscountCode', value: '/admin/api/{SELECTED_VERSION}/price_rules/#{price_rule_id}/discount_codes.json', methods: ["GET", "POST"] },
            { name: 'DiscountCode by Id', value: '/admin/api/{SELECTED_VERSION}/price_rules/#{price_rule_id}/discount_codes/#{discount_code_id}.json', methods: ["GET", "PUT", "DELETE"] },
            { name: 'PriceRule', value: '/admin/api/{SELECTED_VERSION}/price_rules.json', methods: ["GET", "POST"] },
            { name: 'PriceRule by Id', value: '/admin/api/{SELECTED_VERSION}/price_rules/#{price_rule_id}.json', methods: ["GET", "PUT", "DELETE"] },
            { name: 'PriceRule Count', value: '/admin/api/{SELECTED_VERSION}/price_rules/count.json', methods: ["GET"] },
        ]},
        { name: 'Event', value: 'event', paths: [
            { name: 'Event', value: '/admin/api/{SELECTED_VERSION}/events.json', methods: ["GET"] },
            { name: 'Event by Id', value: '/admin/api/{SELECTED_VERSION}/events/#{event_id}.json', methods: ["GET"] },
            { name: 'Event Count', value: '/admin/api/{SELECTED_VERSION}/events/count.json?created_at_min={created_at_min}', methods: ["GET"] },
            { name: 'Webhook', value: '/admin/api/{SELECTED_VERSION}/webhooks.json', methods: ["GET", "POST"] },
            { name: 'Webhook by Id', value: '/admin/api/{SELECTED_VERSION}/webhooks/#{webhook_id}.json', methods: ["GET", "PUT", "DELETE"] },
            { name: 'Webhook Count', value: '/admin/api/{SELECTED_VERSION}/webhooks/count.json', methods: ["GET"] },
        ]},
        { name: 'Inventory', value: 'inventory', paths: [
          { name: 'InventoryItem List', value: '/admin/api/{SELECTED_VERSION}/inventory_items.json?ids={ids_list}', methods: ["GET"] },
          { name: 'InventoryItem by Id', value: '/admin/api/{SELECTED_VERSION}/inventory_items/#{inventory_item_id}.json', methods: ["GET", "PUT"] },
          { name: 'InventoryLevel List', value: '/admin/api/{SELECTED_VERSION}/inventory_levels.json', methods: ["GET"] },
          { name: 'InventoryLevel Delete by Id', value: '/admin/api/{SELECTED_VERSION}/inventory_levels.json?inventory_item_id={inventory_item_id}&location_id={location_id}', methods: ["DELETE"] },
          { name: 'InventoryLevel Connect', value: '/admin/api/{SELECTED_VERSION}/inventory_levels/connect.json', methods: ["POST"] },
          { name: 'InventoryLevel Set', value: '/admin/api/{SELECTED_VERSION}/inventory_levels/set.json', methods: ["POST"] },
          { name: 'InventoryLevel Adjust', value: '/admin/api/{SELECTED_VERSION}/inventory_levels/adjust.json', methods: ["POST"] },
          { name: 'Location List', value: '/admin/api/{SELECTED_VERSION}/locations.json', methods: ["GET"] },
          { name: 'Location By Id', value: '/admin/api/{SELECTED_VERSION}/locations/#{location_id}.json', methods: ["GET"] },
          { name: 'Location InventoryLevel By Id', value: '/admin/api/{SELECTED_VERSION}/locations/#{location_id}/inventory_levels.json', methods: ["GET"] },
          { name: 'Location Count', value: '/admin/api/{SELECTED_VERSION}/locations/count.json', methods: ["GET"] },
        ]},
        { name: 'Marketing Event', value: 'marketing-event', paths: [
          { name: 'MarketingEvent', value: '/admin/api/{SELECTED_VERSION}/marketing_events.json', methods: ["GET", "POST"] },
          { name: 'MarketingEvent by Id', value: '/admin/api/{SELECTED_VERSION}/marketing_events/#{marketing_event_id}.json', methods: ["GET", "PUT", "DELETE"] },
          { name: 'MarketingEvent Engagement by Id', value: '/admin/api/{SELECTED_VERSION}/marketing_events/#{marketing_event_id}/engagements.json', methods: ["POST"] },
          { name: 'MarketingEvent Count', value: '/admin/api/{SELECTED_VERSION}/marketing_events/count.json', methods: ["GET"] },
        ]},
        { name: 'Metafield', value: 'metafield', paths: [] },
        { name: 'Online Store', value: 'online-store', paths: [] },
        { name: 'Order', value: 'order', paths: [
          { name: 'AbandonedCheckout List', value: '/admin/api/{SELECTED_VERSION}/checkouts.json', methods: ["GET"] },
          { name: 'AbandonedCheckout Count', value: '/admin/api/{SELECTED_VERSION}/checkouts/count.json', methods: ["GET"] },
          { name: 'DraftOrder', value: '/admin/api/{SELECTED_VERSION}/checkouts.json', methods: ["GET", "POST"] },
          { name: 'DraftOrder by Id', value: '/admin/api/{SELECTED_VERSION}/draft_orders/#{draft_order_id}.json', methods: ["GET", "PUT", "DELETE"] },
          { name: 'DraftOrder Complete', value: '/admin/api/{SELECTED_VERSION}/draft_orders/#{draft_order_id}/complete.json', methods: ["PUT"] },
          { name: 'DraftOrder SendInvoice', value: '/admin/api/{SELECTED_VERSION}/draft_orders/#{draft_order_id}/send_invoice.json', methods: ["POST"] },
          { name: 'DraftOrder Count', value: '/admin/api/{SELECTED_VERSION}/draft_orders/count.json', methods: ["GET"] },
          { name: 'Order', value: '/admin/api/{SELECTED_VERSION}/orders.json', methods: ["GET", "POST"] },
          { name: 'Order by Id', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}.json', methods: ["GET", "PUT", "DELETE"] },
          { name: 'Order Cancel by Id', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/cancel.json', methods: ["POST"] },
          { name: 'Order Close by Id', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/close.json', methods: ["POST"] },
          { name: 'Order Open by Id', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/open.json', methods: ["POST"] },
          { name: 'Order Count', value: '/admin/api/{SELECTED_VERSION}/orders/count.json', methods: ["GET"] },
          { name: 'OrderRisk', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/risks.json', methods: ["GET", "POST"] },
          { name: 'OrderRisk by Id', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/risks/#{risk_id}.json', methods: ["GET", "PUT", "DELETE"] },
          { name: 'Refund', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/refunds.json', methods: ["GET", "POST"] },
          { name: 'Refund by Id', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/refunds/#{refund_id}.json', methods: ["GET"] },
          { name: 'Refund Calculate', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/refunds/calculate.json', methods: ["POST"] },
          { name: 'Transaction', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/transactions.json', methods: ["GET", "POST"] },
          { name: 'Transaction by Id', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/transactions/#{transaction_id}.json', methods: ["GET"] },
          { name: 'Transaction Count', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/transactions/count.json', methods: ["GET"] },
        ]},
        { name: 'Plus', value: 'plus', paths: [
          { name: 'GiftCard Create', value: '/admin/api/{SELECTED_VERSION}/gift_cards.json', methods: ["POST"] },
          { name: 'GiftCard List', value: '/admin/api/{SELECTED_VERSION}/gift_cards.json?status=enabled', methods: ["GET"] },
          { name: 'GiftCard by Id', value: '/admin/api/{SELECTED_VERSION}/gift_cards/#{gift_card_id}.json', methods: ["GET", "PUT"] },
          { name: 'GiftCard Disable by Id', value: '/admin/api/{SELECTED_VERSION}/gift_cards/#{gift_card_id}/disable.json', methods: ["POST"] },
          { name: 'GiftCard Search', value: '/admin/api/{SELECTED_VERSION}/gift_cards/search.json?query={query}', methods: ["GET"] },
          { name: 'GiftCard Count', value: '/admin/api/{SELECTED_VERSION}/gift_cards/count.json', methods: ["GET"] },
          { name: 'User List', value: '/admin/api/{SELECTED_VERSION}/users.json', methods: ["GET"] },
          { name: 'User by Id', value: '/admin/api/{SELECTED_VERSION}/users/#{user_id}.json', methods: ["GET"] },
          { name: 'User Logged-in List', value: '/admin/api/{SELECTED_VERSION}/users/current.json', methods: ["GET"] },
        ]},
        { name: 'Product', value: 'product', paths: [
          { name: 'Product', value: '/admin/api/{SELECTED_VERSION}/products.json', methods: ["GET", "POST"] },
          { name: 'Product by Id', value: '/admin/api/{SELECTED_VERSION}/products/#{product_id}.json', methods: ["GET", "PUT", "DELETE"] },
          { name: 'Product Count', value: '/admin/api/{SELECTED_VERSION}/products/count.json', methods: ["GET"] },
          { name: 'ProductVariant', value: '/admin/api/{SELECTED_VERSION}/products/#{product_id}/variants.json', methods: ["GET", "POST"] },
          { name: 'ProductVariant by Id', value: '/admin/api/{SELECTED_VERSION}/variants/#{variant_id}.json', methods: ["GET", "PUT"] },
          { name: 'ProductVariant Delete by Id', value: '/admin/api/{SELECTED_VERSION}/products/#{product_id}/variants/#{variant_id}.json', methods: ["DELETE"] },
          { name: 'ProductVariant Count', value: '/admin/api/{SELECTED_VERSION}/products/#{product_id}/variants/count.json', methods: ["GET"] },
          { name: 'ProductImage', value: '/admin/api/{SELECTED_VERSION}/products/#{product_id}/images.json', methods: ["GET", "POST"] },
          { name: 'ProductImage by Id', value: '/admin/api/{SELECTED_VERSION}/products/#{product_id}/images/#{image_id}.json', methods: ["GET", "PUT", "DELETE"] },
          { name: 'ProductImage Count', value: '/admin/api/{SELECTED_VERSION}/products/#{product_id}/images/count.json', methods: ["GET"] },
          { name: 'Collection by Id', value: '/admin/api/{SELECTED_VERSION}/collections/#{collection_id}.json', methods: ["GET"] },
          { name: 'Collection Products by Id', value: '/admin/api/{SELECTED_VERSION}/collections/#{collection_id}/products.json', methods: ["GET"] },
          { name: 'SmartCollection', value: '/admin/api/{SELECTED_VERSION}/smart_collections.json', methods: ["GET", "POST"] },
          { name: 'SmartCollection by Id', value: '/admin/api/{SELECTED_VERSION}/smart_collections/#{smart_collection_id}.json', methods: ["GET", "PUT", "DELETE"] },
          { name: 'SmartCollection Count', value: '/admin/api/{SELECTED_VERSION}/smart_collections/count.json', methods: ["GET"] },
          { name: 'CustomCollection', value: '/admin/api/{SELECTED_VERSION}/custom_collections.json', methods: ["GET", "POST"] },
          { name: 'CustomCollection by Id', value: '/admin/api/{SELECTED_VERSION}/custom_collections/#{custom_collection_id}.json', methods: ["GET", "PUT", "DELETE"] },
          { name: 'CustomCollection Count', value: '/admin/api/{SELECTED_VERSION}/custom_collections/count.json', methods: ["GET"] },
          { name: 'Collect', value: '/admin/api/{SELECTED_VERSION}/collects.json', methods: ["GET", "POST"] },
          { name: 'Collect by Id', value: '/admin/api/{SELECTED_VERSION}/collects/#{collect_id}.json', methods: ["GET", "DELETE"] },
          { name: 'Collect Count', value: '/admin/api/{SELECTED_VERSION}/collects/count.json', methods: ["GET"] },
        ]},
        { name: 'Sales Channel', value: 'sales-channel', paths: [
          { name: 'ProductListing', value: '/admin/api/{SELECTED_VERSION}/product_listings.json', methods: ["GET"] },
          { name: 'ProductListing by Id', value: '/admin/api/{SELECTED_VERSION}/product_listings/#{product_listing_id}.json', methods: ["GET", "PUT", "DELETE"] },
          { name: 'ProductListing Product_IDs', value: '/admin/api/{SELECTED_VERSION}/product_listings/product_ids.json', methods: ["GET"] },
          { name: 'ProductListing Count', value: '/admin/api/{SELECTED_VERSION}/product_listings/count.json', methods: ["GET"] },
          { name: 'CollectionListing', value: '/admin/api/{SELECTED_VERSION}/collection_listings.json', methods: ["GET"] },
          { name: 'CollectionListing by Id', value: '/admin/api/{SELECTED_VERSION}/collection_listings/#{collection_listing_id}.json', methods: ["GET", "PUT", "DELETE"] },
          { name: 'CollectionListing Product_IDs', value: '/admin/api/{SELECTED_VERSION}/collection_listings/#{collection_listing_id}/product_ids.json', methods: ["GET"] },
          { name: 'Payment', value: '/admin/api/{SELECTED_VERSION}/checkouts/#{token}/payments.json', methods: ["GET", "POST"] },
          { name: 'Payment by Id', value: '/admin/api/{SELECTED_VERSION}/checkouts/#{token}/payments/#{payment_id}.json', methods: ["GET"] },
          { name: 'Payment Count', value: '/admin/api/{SELECTED_VERSION}/checkouts/#{token}/payments/count.json', methods: ["GET"] },
          { name: 'Checkout Create', value: '/admin/api/{SELECTED_VERSION}/checkouts.json', methods: ["POST"] },
          { name: 'Checkout by Id', value: '/admin/api/{SELECTED_VERSION}/checkouts/#{token}.json', methods: ["GET", "PUT"] },
          { name: 'Checkout Complete', value: '/admin/api/{SELECTED_VERSION}/checkouts/#{token}/complete.json', methods: ["POST"] },
          { name: 'Checkout ShippingRates by Id', value: '/admin/api/{SELECTED_VERSION}/checkouts/#{token}/shipping_rates.json', methods: ["GET"] },
          { name: 'ResourceFeedback', value: '/admin/api/{SELECTED_VERSION}/resource_feedback.json', methods: ["GET", "POST"] },
        ]},
        { name: 'Shipping and Fulfillment', value: 'shipping-and-fulfillment', paths: [
          { name: 'FulfillmentEvent', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/fulfillments/#{fulfillment_id}/events.json', methods: ["GET", "POST"] },
          { name: 'FulfillmentEvent by Id', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/fulfillments/#{fulfillment_id}/events/#{event_id}.json', methods: ["GET", "DELETE"] },
          { name: 'FulfillmentOrder', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/fulfillment_orders.json', methods: ["GET"] },
          { name: 'FulfillmentOrder by Id', value: '/admin/api/{SELECTED_VERSION}/fulfillment_orders/#{fulfillment_order_id}.json', methods: ["GET"] },
          { name: 'FulfillmentOrder Cancel by Id', value: '/admin/api/{SELECTED_VERSION}/fulfillment_orders/#{fulfillment_order_id}/cancel.json', methods: ["POST"] },
          { name: 'FulfillmentOrder Close by Id', value: '/admin/api/{SELECTED_VERSION}/fulfillment_orders/#{fulfillment_order_id}/close.json', methods: ["POST"] },
          { name: 'FulfillmentOrder Move by Id', value: '/admin/api/{SELECTED_VERSION}/fulfillment_orders/#{fulfillment_order_id}/move.json', methods: ["POST"] },
          { name: 'CancellationRequest', value: '/admin/api/{SELECTED_VERSION}/fulfillment_orders/#{fulfillment_order_id}/cancellation_request.json', methods: ["POST"] },
          { name: 'CancellationRequest Accept', value: '/admin/api/{SELECTED_VERSION}/fulfillment_orders/#{fulfillment_order_id}/cancellation_request/accept.json', methods: ["POST"] },
          { name: 'CancellationRequest Reject', value: '/admin/api/{SELECTED_VERSION}/fulfillment_orders/#{fulfillment_order_id}/cancellation_request/reject.json', methods: ["POST"] },
          { name: 'Fulfillment', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/fulfillments.json', methods: ["GET", "POST"] },
          { name: 'Fulfillment by OrderId', value: '/admin/api/{SELECTED_VERSION}/fulfillment_orders/#{fulfillment_order_id}/fulfillments.json', methods: ["GET"] },
          { name: 'Fulfillment by Id', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/fulfillments/#{fulfillment_id}.json', methods: ["GET", "PUT"] },
          { name: 'Fulfillment Cancel by Id', value: '/admin/api/{SELECTED_VERSION}/fulfillments/#{fulfillment_id}/cancel.json', methods: ["POST"] },
          { name: 'Fulfillment Create', value: '/admin/api/{SELECTED_VERSION}/fulfillments.json', methods: ["POST"] },
          { name: 'Fulfillment Update Tracking', value: '/admin/api/{SELECTED_VERSION}/fulfillments/#{fulfillment_id}/update_tracking.json', methods: ["POST"] },
          { name: 'Fulfillment Complete', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/fulfillments/#{fulfillment_id}/complete.json', methods: ["POST"] },
          { name: 'Fulfillment Open', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/fulfillments/#{fulfillment_id}/open.json', methods: ["POST"] },
          { name: 'Fulfillment Cancel', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/fulfillments/#{fulfillment_id}/cancel.json', methods: ["POST"] },
          { name: 'Fulfillment Count', value: '/admin/api/{SELECTED_VERSION}/orders/#{order_id}/fulfillments/count.json', methods: ["GET"] },
          { name: 'FulfillmentRequest', value: '/admin/api/{SELECTED_VERSION}/fulfillment_orders/#{fulfillment_order_id}/fulfillment_request.json', methods: ["POST"] },
          { name: 'FulfillmentRequest Accept', value: '/admin/api/{SELECTED_VERSION}/fulfillment_orders/#{fulfillment_order_id}/fulfillment_request/accept.json', methods: ["POST"] },
          { name: 'FulfillmentRequest Reject', value: '/admin/api/{SELECTED_VERSION}/fulfillment_orders/#{fulfillment_order_id}/fulfillment_request/reject.json', methods: ["POST"] },
          { name: 'CarrierService', value: '/admin/api/{SELECTED_VERSION}/carrier_services.json', methods: ["GET", "POST"] },
          { name: 'CarrierService by Id', value: '/admin/api/{SELECTED_VERSION}/carrier_services/#{carrier_service_id}.json', methods: ["GET", "PUT", "DELETE"] },
          { name: 'FulfillmentService', value: '/admin/api/{SELECTED_VERSION}/fulfillment_services.json', methods: ["GET", "POST"] },
          { name: 'FulfillmentService by Id', value: '/admin/api/{SELECTED_VERSION}/fulfillment_services/#{fulfillment_service_id}.json', methods: ["GET", "PUT", "DELETE"] },
          { name: 'LocationsForMove', value: '/admin/api/{SELECTED_VERSION}/fulfillment_orders/#{fulfillment_order_id}/locations_for_move.json', methods: ["GET"] },
        ]},
        { name: 'Shopify Payments', value: 'shopify-payments', paths: [
          { name: 'Transactions by PayoutId', value: '/admin/api/{SELECTED_VERSION}/shopify_payments/balance/transactions.json?payout_id={payout_id}', methods: ["GET"] },
          { name: 'Dispute', value: '/admin/api/{SELECTED_VERSION}/shopify_payments/disputes.json', methods: ["GET"] },
          { name: 'Dispute by Id', value: '/admin/api/{SELECTED_VERSION}/shopify_payments/disputes/#{dispute_id}.json', methods: ["GET"] },
          { name: 'Payouts', value: '/admin/api/{SELECTED_VERSION}/shopify_payments/payouts.json', methods: ["GET"] },
          { name: 'Payouts by Id', value: '/admin/api/{SELECTED_VERSION}/shopify_payments/payouts/#{payout_id}.json', methods: ["GET"] },
          { name: 'Balance', value: '/admin/api/{SELECTED_VERSION}/shopify_payments/balance.json', methods: ["GET"] },
        ]},
        { name: 'Store Property', value: 'store-property', paths: [
          { name: 'Shop', value: '/admin/api/{SELECTED_VERSION}/shop.json', methods: ["GET"] },
          { name: 'Country', value: '/admin/api/{SELECTED_VERSION}/countries.json', methods: ["GET", "POST"] },
          { name: 'Country by Id', value: '/admin/api/{SELECTED_VERSION}/countries/#{country_id}.json', methods: ["GET", "PUT", "DELETE"] },
          { name: 'Country Count', value: '/admin/api/{SELECTED_VERSION}/countries/count.json', methods: ["GET"] },
          { name: 'Province', value: '/admin/api/{SELECTED_VERSION}/countries/#{country_id}/provinces.json', methods: ["GET", "POST"] },
          { name: 'Province by Id', value: '/admin/api/{SELECTED_VERSION}/countries/#{country_id}/provinces/#{province_id}.json', methods: ["GET", "PUT"] },
          { name: 'Province Count', value: '/admin/api/{SELECTED_VERSION}/countries/#{country_id}/provinces/count.json', methods: ["GET"] },
          { name: 'Policy', value: '/admin/api/{SELECTED_VERSION}/policies.json', methods: ["GET"] },
          { name: 'Currency', value: '/admin/api/{SELECTED_VERSION}/currencies.json', methods: ["GET"] },
        ]},
        { name: 'Tender Transaction', value: 'tender-transaction', paths: [
          { name: 'TenderTransaction List', value: '/admin/api/{SELECTED_VERSION}/tender_transactions.json', methods: ["GET"] },
        ]},
    ],
    versions:[
      '2020-04', '2020-01', '2019-10', '2019-07', '2019-04'
    ],
    regions: [
        { name: 'Canada', value: 'ca' },
        { name: 'United States', value: 'us' },
        { name: 'United Kingdom', value: 'uk' },
        { name: 'Japan', value: 'jp' },
    ]
};
