export default [
  {
    "name": "Men+s+Tech+Shell+Full-Zip",
    "title": "Men's Tech Shell Full-Zip",
    "category": "mens_outerwear",
    "quantity": 294,
    "added_date": "2020-01-01",
    "status": "active",
    "price": 50.2,
    "description": "A versatile full-zip that you can wear all day long and even to the gym. This technical shell features moisture-wicking fabric, added stretch and a hidden pocket for your smartphone or media player.&amp;nbsp;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;100% polyester.&lt;/li&gt;&lt;li&gt;Smooth, technical front with textured mesh back.&lt;/li&gt;&lt;li&gt;Drawstring bottom for adjustable fit.&lt;/li&gt;&lt;li&gt;Raglan sleeves.&lt;/li&gt;&lt;li&gt;Available in forest green with the white Google logo embroidered at left chest.&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;",
    "image": "10-15068B.jpg",
    "largeImage": "10-15068A.jpg"
  },
  {
    "name": "Anvil+L+S+Crew+Neck+-+Grey",
    "title": "Anvil L/S Crew Neck - Grey",
    "category": "mens_outerwear",
    "quantity": 189,
    "added_date": "2020-01-02",
    "status": "active",
    "price": 22.15,
    "description": "You'll be swooning over this crew neck as soon as you feel how soft it is.&amp;nbsp;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;40% preshrunk ring-spun cotton, 60% polyester terry fleece.&amp;nbsp;&lt;/li&gt;&lt;li&gt;Available in dark heather charcoal with the white Google logo screen printed across center chest.&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;",
    "image": "10-14154B.jpg",
    "largeImage": "10-14154A.jpg"
  },
  {
    "name": "Green+Flex+Fleece+Zip+Hoodie",
    "title": "Green Flex Fleece Zip Hoodie",
    "category": "mens_outerwear",
    "quantity": 438,
    "added_date": "2020-01-03",
    "status": "active",
    "price": 45.65,
    "description": "Ultra soft. Ultra cozy. Our popular flex fleece hoodie now available in speckled green.&amp;nbsp;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;50% cotton / 50% polyester.&amp;nbsp;&lt;/li&gt;&lt;li&gt;Made in the USA.&amp;nbsp;&lt;/li&gt;&lt;li&gt;Full-zip.&amp;nbsp;&lt;/li&gt;&lt;li&gt;Available in green with specks of blue and the white Google logo embroidered at left bicep.&amp;nbsp;&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;",
    "image": "10-14157B.jpg",
    "largeImage": "10-14157A.jpg"
  },
  {
    "name": "Android+Nylon+Packable+Jacket",
    "title": "Android Nylon Packable Jacket",
    "category": "mens_outerwear",
    "quantity": 196,
    "added_date": "2020-01-04",
    "status": "active",
    "price": 33.6,
    "description": "Pack. Pack. Pack it up! This nylon jacket with reflective trim can literally be packed into itself in seconds. Features a waterproof nylon fabric, Android eyes &amp;amp; antennaes on the hood and a  carrying strap when jacket is fully packed. Android robot is printed on back above zipper in a reflective, metallic finish.",
    "image": "10-15041B.jpg",
    "largeImage": "10-15041A.jpg"
  },
  {
    "name": "YouTube+Ultimate+Hooded+Sweatshirt",
    "title": "YouTube Ultimate Hooded Sweatshirt",
    "category": "mens_outerwear",
    "quantity": 317,
    "added_date": "2020-01-05",
    "status": "active",
    "price": 32.35,
    "description": "Stay warm in this cozy hoodie made of 50% cotton and 50% polyester. This comfortable design features set in sleeves, dyed to match draw cord and a front pouch pocket. Available in Charcoal with the full color YouTube logo screen printed across the chest. Unisex sizing.",
    "image": "10-14133B.jpg",
    "largeImage": "10-14133A.jpg"
  },
  {
    "name": "Grey+Heather+Fleece+Zip+Hoodie",
    "title": "Grey Heather Fleece Zip Hoodie",
    "category": "mens_outerwear",
    "quantity": 92,
    "added_date": "2020-01-06",
    "status": "active",
    "price": 38.85,
    "description": "Cozy up with this full-zip hoodie.&amp;nbsp;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;60% combed, ring-spun cotton, 40% polyester.&lt;/li&gt;&lt;li&gt;Unisex sizing.&lt;/li&gt;&lt;li&gt;Retail fit.&lt;/li&gt;&lt;li&gt;Contrast zipper.&lt;/li&gt;&lt;li&gt;Kangaroo pockets with ribbed cuffs and waistband.&lt;/li&gt;&lt;li&gt;Available in dark heather with the white Google logo embroidered at left chest.&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;",
    "image": "10-14160B.jpg",
    "largeImage": "10-14160A.jpg"
  },
  {
    "name": "Vastrm+Hoodie",
    "title": "Vastrm Hoodie",
    "category": "mens_outerwear",
    "quantity": 266,
    "added_date": "2020-01-07",
    "status": "active",
    "price": 200,
    "description": "The ultimate in fit and fabric, this Vastrm hoodie doesn't disappoint. Made from soft pique fabric, the lightweight full-zip features a halfmoon accent and matching hoodie strings.&amp;nbsp;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Additional Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;100% cotton.&lt;/li&gt;&lt;li&gt;Hidden phone pocket neatly cradles your digital device.&amp;nbsp;&lt;/li&gt;&lt;li&gt;Available in charcoal grey with red strings and hood. White Google logo is embroidered at left bicep.&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;",
    "image": "10-14153B.jpg",
    "largeImage": "10-14153A.jpg"
  },
  {
    "name": "Recycled+Plastic+Bottle+Hoodie+-+Green",
    "title": "Recycled Plastic Bottle Hoodie - Green",
    "category": "mens_outerwear",
    "quantity": 211,
    "added_date": "2020-01-08",
    "status": "deactivated",
    "price": 60.95,
    "description": "Ever wonder where all of the disposable water bottles of the world end up? We know some of them are reused for a second purpose. Each of these hoodies contain approximately 9 recycled water bottles that are woven into the fabric.&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Features:&amp;nbsp;&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;50% recycled cotton, 50% recycled polyester.&lt;/li&gt;&lt;li&gt;Full zipper and orange drawstring pulls.&lt;/li&gt;&lt;li&gt;USA made.&amp;nbsp;&lt;/li&gt;&lt;li&gt;&amp;nbsp;Available in forest green with the white Google logo embroidered at left bicep.&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;",
    "image": "10-14158B.jpg",
    "largeImage": "10-14158A.jpg"
  },
  {
    "name": "Rowan+Pullover+Hood",
    "title": "Rowan Pullover Hood",
    "category": "mens_outerwear",
    "quantity": 426,
    "added_date": "2020-01-09",
    "status": "active",
    "price": 60.85,
    "description": "In search of the perfect layering piece? This lightweight, triblend pullover is ultra soft and ideal for all seasons.&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;50% polyester, 38% cotton, 12% rayon triblend.&lt;/li&gt;&lt;li&gt;Available in black with the white Google logo screenprinted at left bicep.&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;",
    "image": "10-14152B.jpg",
    "largeImage": "10-14152A.jpg"
  },
  {
    "name": "Men+s+Voyage+Fleece+Jacket",
    "title": "Men's Voyage Fleece Jacket",
    "category": "mens_outerwear",
    "quantity": 266,
    "added_date": "2020-01-10",
    "status": "active",
    "price": 48,
    "description": "&lt;div&gt;Perhaps the equivalent to that comfort blanket you had years ago is a cozy fleece. This full-zip is the perfect layering piece for those 'in-between' months when mother nature just can't make up her mind.&amp;nbsp;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;100% polyester anti-pill yarn fleece.&lt;/li&gt;&lt;li&gt;100% polyester taffeta lining in sleeves.&lt;/li&gt;&lt;li&gt;Tricot-lined lower pockets with reverse coil zippers.&lt;/li&gt;&lt;li&gt;Available in black with the white Google logo embroidered at left chest.&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;",
    "image": "10-14155B.jpg",
    "largeImage": "10-14155A.jpg"
  },
  {
    "name": "Eco-Jersey+Chrome+Zip+Up+Hoodie",
    "title": "Eco-Jersey Chrome Zip Up Hoodie",
    "category": "mens_outerwear",
    "quantity": 376,
    "added_date": "2020-01-11",
    "status": "active",
    "price": 37.75,
    "description": "An exceptionally soft, eco-friendly full-zip for picture-perfect layering.&amp;nbsp;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;50% polyester, 38% cotton (6.25% recycled), 12% rayon (6.25% organic).&lt;/li&gt;&lt;li&gt;Low-impact yarn dyed and washed.&lt;/li&gt;&lt;li&gt;Brushed nickel zipper with natural taping.&lt;/li&gt;&lt;li&gt;Split front pouch pocket.&amp;nbsp;&lt;/li&gt;&lt;li&gt;Available in deep pacific blue with the white Google Chrome logo screenprinted at left chest.&amp;nbsp;&lt;/li&gt;&lt;/ul&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;/div&gt;",
    "image": "10-14159B.jpg",
    "largeImage": "10-14159A.jpg"
  },
  {
    "name": "Android+Colorblock+Hooded+Pullover",
    "title": "Android Colorblock Hooded Pullover",
    "category": "mens_outerwear",
    "quantity": 109,
    "added_date": "2020-01-12",
    "status": "active",
    "price": 50.2,
    "description": "This cozy Android hoodie features a sublimated camo design printed inside hood and along inner sleeves and side panels.  Moisture-wicking polyester fabric keeps you cool and dry.&amp;nbsp;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;100% polyester.&lt;/li&gt;&lt;li&gt;Ultra soft, fleece interior.&amp;nbsp;&lt;/li&gt;&lt;li&gt;Available in smoke/lime green with the white Android robot embroidered at left chest.&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;",
    "image": "10-14146B.jpg",
    "largeImage": "10-14146A.jpg"
  },
  {
    "name": "Tri-blend+Full-Zip+Hoodie",
    "title": "Tri-blend Full-Zip Hoodie",
    "category": "mens_outerwear",
    "quantity": 426,
    "added_date": "2020-01-13",
    "status": "active",
    "price": 52.2,
    "description": "Comfy cool. This canvas tri-blend full-zip hoodie made of a poly/cotton/rayon blend is sure to please the eyes as well as the senses. Made in the USA. Available in Black with the white Google logo embroidered at left chest.",
    "image": "10-14216B.jpg",
    "largeImage": "10-14216A.jpg"
  },
  {
    "name": "Fleece+Full-Zip+Hoodie",
    "title": "Fleece Full-Zip Hoodie",
    "category": "mens_outerwear",
    "quantity": 260,
    "added_date": "2020-01-14",
    "status": "active",
    "price": 45.65,
    "description": "If you find that the 'spark' is missing from your outfit, you may need to add one of these full-zip hoodies to the mix. Resurfacing from 1989, this colorful full-zip features a sporty fit with ultra soft fleece lining.&lt;div&gt;&lt;br&gt;&lt;div&gt;Additional Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;50% polyester and 50% cotton fleece.&amp;nbsp;&lt;/li&gt;&lt;li&gt;Available in blue with the Google logo embroidered in white at left bicep.&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;&lt;/div&gt;",
    "image": "10-14215B.jpg",
    "largeImage": "10-14215A.jpg"
  },
  {
    "name": "Jacquard-Knit+Full-Zip+Fleece",
    "title": "Jacquard-Knit Full-Zip Fleece",
    "category": "mens_outerwear",
    "quantity": 233,
    "added_date": "2020-01-15",
    "status": "active",
    "price": 74.9,
    "description": "We love color contrast, especially in Google Blue! This textured jacket features a jacquard texture with contrast stitching and zippers.&amp;nbsp;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Additional Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;100% polyester.&amp;nbsp;&lt;/li&gt;&lt;li&gt;Audio port access available on inside left pocket.&lt;/li&gt;&lt;li&gt;Available in Carbon/Olympic Blue with the Google logo embroidered in white on left chest.&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;",
    "image": "10-14217B.jpg",
    "largeImage": "10-14217A.jpg"
  },
  {
    "name": "YouTube+Unisex+Flex+Fleece+Zip+Hoodie",
    "title": "YouTube Unisex Flex Fleece Zip Hoodie",
    "category": "mens_outerwear",
    "quantity": 249,
    "added_date": "2020-01-16",
    "status": "active",
    "price": 45.25,
    "description": "Our popular flex fleece hoodie, now for YouTube fans everywhere.&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;50% polyester, 50% cotton fleece.&lt;/li&gt;&lt;li&gt;Sporty, unisex fit.&lt;/li&gt;&lt;li&gt;Metal zipper.&lt;/li&gt;&lt;li&gt;Hood.&lt;/li&gt;&lt;li&gt;Available in dark heather grey with the YouTube logo embroidered at left bicep.&lt;/li&gt;&lt;/ul&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;/div&gt;",
    "image": "10-15103B.jpg",
    "largeImage": "10-15103A.jpg"
  },
  {
    "name": "Ladies+Modern+Stretch+Full+Zip",
    "title": "Ladies Modern Stretch Full Zip",
    "category": "ladies_outerwear",
    "quantity": 484,
    "added_date": "2020-01-17",
    "status": "deactivated",
    "price": 41.6,
    "description": "With an updated fit and figure-flattering details, this full-zip combines ultra soft cotton with a dash of spandex to retain its shape all day long.&amp;nbsp;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;96% cotton, 4% spandex.&lt;/li&gt;&lt;li&gt;Gently contoured silhouette &amp;amp; longer length design for a style that moves with you.&lt;/li&gt;&lt;li&gt;Self-fabric hood.&lt;/li&gt;&lt;li&gt;Dyed-to-match zipper.&amp;nbsp;&lt;/li&gt;&lt;li&gt;Front slash pockets.&lt;/li&gt;&lt;li&gt;Open cuffs &amp;amp; hem.&lt;/li&gt;&lt;li&gt;Available in Mosaic Blue with the white Google logo embroidered at left chest.&amp;nbsp;&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;",
    "image": "10-24102B.jpg",
    "largeImage": "10-24102A.jpg"
  },
  {
    "name": "Ladies+Colorblock+Wind+Jacket",
    "title": "Ladies Colorblock Wind Jacket",
    "category": "ladies_outerwear",
    "quantity": 24,
    "added_date": "2020-01-18",
    "status": "active",
    "price": 45.9,
    "description": "Brighten up your commute on gloomy days. This lightweight jacket features a subtle grid texture and a punch of bright pink at each side panel.&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;100% polyester dobby shell with jersey lining.&lt;/li&gt;&lt;li&gt;Packable zip-in hood with contrast pink zipper.&lt;/li&gt;&lt;li&gt;Cadet collar and elastic cuffs.&lt;/li&gt;&lt;li&gt;Adjustable toggles at waist can be cinched for a flattering fit.&lt;/li&gt;&lt;li&gt;Available in grey/dark rose with the white Google logo embroidered at left chest.&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;",
    "image": "10-25058B.jpg",
    "largeImage": "10-25058A.jpg"
  },
  {
    "name": "Ladies+Voyage+Fleece+Jacket",
    "title": "Ladies Voyage Fleece Jacket",
    "category": "ladies_outerwear",
    "quantity": 491,
    "added_date": "2020-01-19",
    "status": "active",
    "price": 48,
    "description": "&lt;div&gt;Perhaps the equivalent to that comfort blanket you had years ago is a cozy fleece. This full-zip is the perfect layering piece for those 'in-between' months when mother nature just can't make up her mind.&amp;nbsp;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;100% polyester anti-pill yarn fleece.&lt;/li&gt;&lt;li&gt;100% polyester taffeta lining in sleeves.&lt;/li&gt;&lt;li&gt;Tricot-lined lower pockets with reverse coil zippers.&lt;/li&gt;&lt;li&gt;Available in purple with the white Google logo embroidered at left chest.&lt;/li&gt;&lt;li&gt;&lt;b&gt;Please note! Sizing runs larger than normal. Consider ordering a size smaller than normal.&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;",
    "image": "10-24101B.jpg",
    "largeImage": "10-24101A.jpg"
  },
  {
    "name": "Ladies+Pullover+L+S+Hood",
    "title": "Ladies Pullover L/S Hood",
    "category": "ladies_outerwear",
    "quantity": 471,
    "added_date": "2020-01-20",
    "status": "active",
    "price": 36.5,
    "description": "A longsleeve layering piece with a hood. What more can you ask for between season changes?&amp;nbsp;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;85% polyester, 15% cotton.&lt;/li&gt;&lt;li&gt;Ultra lightweight, tissue jersey fabric.&lt;/li&gt;&lt;li&gt;Scoop-neck with hood.&lt;/li&gt;&lt;li&gt;Available in jewel blue with the white Google logo screenprinted across center chest.&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;",
    "image": "10-24098B.jpg",
    "largeImage": "10-24098A.jpg"
  },
  {
    "name": "Ladies+Sonoma+Hybrid+Knit+Jacket",
    "title": "Ladies Sonoma Hybrid Knit Jacket",
    "category": "ladies_outerwear",
    "quantity": 444,
    "added_date": "2020-01-21",
    "status": "active",
    "price": 84.85,
    "description": "A modern styled sport jacket that combines a classic silhouette with moisture-wicking fabrics. Technical features include a reversed coil zipper with reflective stripe, interior media exit port, and built-in media pocket.&amp;nbsp;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Additional Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;94% polyester, 6% spandex.&lt;/li&gt;&lt;li&gt;Available in black with the white Google logo heat transferred onto right hip along zipper.&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;",
    "image": "10-24097B.jpg",
    "largeImage": "10-24097A.jpg"
  },
  {
    "name": "Ladies+Yerba+Knit+Quarter+Zip",
    "title": "Ladies Yerba Knit Quarter Zip",
    "category": "ladies_outerwear",
    "quantity": 246,
    "added_date": "2020-01-22",
    "status": "active",
    "price": 64.2,
    "description": "This on-trend quarter zip doubles as workout gear.&amp;nbsp;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Features:&lt;/div&gt;&lt;div&gt;&lt;ul&gt;&lt;li&gt;81% polyester, 19% spandex jersey knit.&lt;/li&gt;&lt;li&gt;Textured knit fabric features a moisture-wicking finish.&lt;/li&gt;&lt;li&gt;Exposed contrast reverse coil zipper with contrast inner collar.&lt;/li&gt;&lt;li&gt;Lightweight design with added stretch.&lt;/li&gt;&lt;li&gt;Available in heathered indigo with the white Google logo heat transferred vertically onto front right hip.&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;",
    "image": "10-24099B.jpg",
    "largeImage": "10-24099A.jpg"
  }
]
